// packages/integration-svelte/src/client-provider/client-provider.svelte
<script lang="ts">
  import { setContext } from 'svelte';
  import { createClient, defaultStorage } from '@micro-stacks/client';
  import { CLIENT_CONTEXT } from '../common';
  import type { ClientConfig, MicroStacksClient } from '@micro-stacks/client';

  export let appName: ClientConfig['appName'] = undefined;
  export let appIconUrl: ClientConfig['appIconUrl'] = undefined;
  export let storage: ClientConfig['storage'] = defaultStorage;
  export let network: ClientConfig['network'] = undefined;
  export let dehydratedState: ClientConfig['dehydratedState'] = undefined;
  export let onPersistState: ClientConfig['onPersistState'] = undefined;
  export let onSignOut: ClientConfig['onSignOut'] = undefined;
  export let onAuthentication: ClientConfig['onAuthentication'] = undefined;
  export let onNoWalletFound: ClientConfig['onNoWalletFound'] = undefined;
  export let fetcher: ClientConfig['fetcher'] = undefined;
  export let client: MicroStacksClient | undefined = undefined;

  setContext(CLIENT_CONTEXT, createClient({
    client,
    config: {
      appName,
      appIconUrl,
      storage,
      network,
      dehydratedState,
      onPersistState,
      onSignOut,
      onAuthentication,
      onNoWalletFound,
      fetcher
    }
  }));
</script>

<slot/>

// packages/react/src/components/client-provider.tsx
import * as React from 'react';
import { ClientConfig, defaultStorage, getClient } from '@micro-stacks/client';
import { MicroStacksClientContext } from '../common/context';
import {
  useOnAuthenticationEffect,
  useOnPersistEffect,
  useOnSignOutEffect,
} from '../hooks/use-client-callbacks';
import { memo } from 'react';

/** ------------------------------------------------------------------------------------------------------------------
 *   CallbacksProvider (private)
 *  ------------------------------------------------------------------------------------------------------------------
 */

const CallbacksProvider: React.FC<
  Pick<ClientConfig, 'onAuthentication' | 'onSignOut' | 'onPersistState'>
> = memo(({ onPersistState, onAuthentication, onSignOut }) => {
  useOnAuthenticationEffect(onAuthentication);
  useOnSignOutEffect(onSignOut);
  useOnPersistEffect(onPersistState);
  return null;
});

/** ------------------------------------------------------------------------------------------------------------------
 *   ClientProvider
 *  ------------------------------------------------------------------------------------------------------------------
 */

export const ClientProvider: React.FC<
  {
    client?: ReturnType<typeof getClient>;
  } & ClientConfig
> = React.memo(
  ({
    children,
    client: client_,
    dehydratedState,
    appIconUrl,
    appName,
    network,
    storage = defaultStorage,
    onPersistState,
    onAuthentication,
    onSignOut,
  }) => {
    const client =
      client_ ??
      getClient({
        appName,
        appIconUrl,
        dehydratedState,
        network,
        storage,
        onPersistState,
        onAuthentication,
        onSignOut,
      });
    return (
      <MicroStacksClientContext.Provider value={client}>
        {!client_ ? (
          <CallbacksProvider
            onPersistState={onPersistState}
            onAuthentication={onAuthentication}
            onSignOut={onSignOut}
          />
        ) : null}
        {children}
      </MicroStacksClientContext.Provider>
    );
  }
);
